name: 'Setup Gradle'
description: 'Setup Gradle with default configuration for this project'

inputs:
  gradle-home-cache-cleanup:
    description: 'Whether to clean up Gradle home cache'
    required: false
    default: 'true'
  gradle-version:
    description: 'Gradle version to use (if not using wrapper)'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Setup Gradle
      uses: gradle/actions/setup-gradle@5e2ebd065dc2488b7a6ad670704656cbbe1e8f60 # v6.1.1
      with:
        gradle-home-cache-cleanup: ${{ inputs.gradle-home-cache-cleanup }}
        gradle-version: ${{ inputs.gradle-version }}