version: 2
jobs:
  build:
    docker:
      - image: circleci/android:api-28
        auth:
          username: $DOCKERHUB_USERNAME
          password: $DOCKERHUB_PASSWORD
    environment:
      JAVA_OPTS: -Xmx3584m
      GRADLE_OPTS: '-Dorg.gradle.jvmargs="-Xmx3584m -XX:MaxPermSize=512m -XX:+HeapDumpOnOutOfMemoryError" -Dorg.gradle.daemon=false -Dorg.gradle.parallel=false'
    steps:
      - checkout
      - restore_cache:
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Download Dependencies
          command: ./gradlew androidDependencies
      - save_cache:
          paths:
            - ~/.gradle
          key: jars-{{ checksum "build.gradle" }}-{{ checksum  "app/build.gradle" }}
      - run:
          name: Run Tests
          command: |
            ./gradlew test jacocoTestReports
            bash <(curl -s https://codecov.io/bash)