[versions]
activity-compose = "1.9.2"
compose-material = "1.7.3"
kotlin = "2.0.20"

[libraries]
kotlin-stdlib = { group = "org.jetbrains.kotlin", name = "kotlin-stdlib", version.ref = "kotlin"}
compose-material-icon-core = { group = "androidx.compose.material", name = "material-icons-core", version.ref = "compose-material"}
activity-compose = { group = "androidx.activity", name = "activity-compose", version.ref = "activity-compose"}

[plugins]
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
