name: 'Setup Android SDK'
description: 'Setup the Android SDK with default configuration for this project'

inputs:
  packages:
    description: 'Android SDK packages to install'
    required: false
    default: 'platform-tools'

runs:
  using: 'composite'
  steps:
    - name: Setup Android SDK
      uses: android-actions/setup-android@be39fa834029ff78f1a44aa3bb0819b8fc2bd8fd # v4.0.4
      with:
        packages: ${{ inputs.packages }}
