name: 'Setup Java'
description: 'Setup Java with default configuration for this project'

inputs:
  java-version:
    description: 'Java version to setup'
    required: false
    default: '17'
  distribution:
    description: 'Java distribution to use'
    required: false
    default: 'temurin'
  cache:
    description: 'Package manager to cache'
    required: false
    default: 'gradle'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK ${{ inputs.java-version }}
      uses: actions/setup-java@be666c2fcd27ec809703dec50e508c2fdc7f6654 # v5
      with:
        java-version: ${{ inputs.java-version }}
        distribution: ${{ inputs.distribution }}
        cache: ${{ inputs.cache }}