name: 'Setup Java'
description: 'Setup Java with default configuration for this project'

runs:
  using: 'composite'
  steps:
    - name: Set up JDK 17
      uses: actions/setup-java@dded0888837ed1f317902acf8a20df0ad188d165 # v5
      with:
        java-version: '17'
        distribution: 'temurin'
        cache: 'gradle'