name: Android Lint

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  lint:
    name: Run Android Lint
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6

      - name: Set up JDK
        uses: ./.github/actions/setup-java

      - name: Inject secrets into local.properties
        run: echo "reward.server.url=${{ secrets.REWARD_SERVER_URL }}" >> local.properties

      - name: Run Android Lint
        run: ./gradlew lintDebug
