name: Detekt

on:
  pull_request:
    types: [ opened, synchronize, reopened ]

jobs:
  detekt:
    name: Run Detekt
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Set up JDK
        uses: ./.github/actions/setup-java

      - name: Run Detekt
        run: ./gradlew detekt detektCustomRules
