name: screenshot-comparison-comment

on:
  workflow_run:
    workflows:
      - screenshot-comparison
    types:
      - completed

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref }}-${{ github.event.workflow_run.id }}
  cancel-in-progress: true

jobs:
  screenshot-comparison-comment:
    if: >
      github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success'

    timeout-minutes: 2

    permissions:
      actions: read # for downloading artifacts
      contents: write # for pushing screenshot-diff to companion branch
      pull-requests: write # for creating a comment on pull requests

    runs-on: ubuntu-latest

    steps:
      - name: main checkout
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5
        with:
          ref: main

      - uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          name: pr
          run_id: ${{ github.event.workflow_run.id }}
      - id: get-pull-request-number
        name: Get pull request number
        shell: bash
        run: |
          echo "pull_request_number=$(cat NR)" >> "$GITHUB_OUTPUT"

      - uses: dawidd6/action-download-artifact@09f2f74827fd3a8607589e5ad7f9398816f540fe # v3.1.4
        with:
          run_id: ${{ github.event.workflow_run.id }}
          name: screenshot-diff-reports
          path: screenshot-diff-reports
      - id: collect-compare-images
        run: |
          files=$(find . -type f -name '*_compare.png' | sort)
          delimiter="$(openssl rand -hex 8)"
          {
            echo "screenshot_compare_images<<${delimiter}"
            echo "$files"
            echo "${delimiter}"
          } >> "$GITHUB_OUTPUT"

      - name: Prepare companion branch and outputs
        id: prepare-companion-branch
        if: steps.collect-compare-images.outputs.screenshot_compare_images != ''
        env:
          BRANCH_NAME: companion_${{ github.event.workflow_run.head_branch }}
        run: |
          delimiter="$(openssl rand -hex 8)"
          {
            echo "comment_content<<${delimiter}"
            echo "## Screenshot Comparison Results"
          } >> "$GITHUB_OUTPUT"

          # orphan means it will create no history branch
          git branch -D "$BRANCH_NAME" || true
          git checkout --orphan "$BRANCH_NAME"
          git rm -rf .
          echo "${{ steps.collect-compare-images.outputs.screenshot_compare_images }}" | while read file; do
            [ -n "$file" ] && git add "$file"
            echo "![](https://github.com/${{ github.repository }}/blob/${BRANCH_NAME}/$(echo "${file}" | sed 's|^\./||')?raw=true)" >> "$GITHUB_OUTPUT"
          done
          echo "${delimiter}" >> "$GITHUB_OUTPUT"
          git config --global user.name github-actions[bot]
          git config --global user.email github-actions[bot]@users.noreply.github.com
          git commit -m "Add screenshot diff"
          git push origin HEAD:"$BRANCH_NAME" -f

      - name: Find Comment
        uses: peter-evans/find-comment@3eae4d37986fb5a8592848f6a574fdf654e61f9e # v3
        id: fc
        if: steps.prepare-companion-branch.outputs.comment_content != ''
        with:
          issue-number: ${{ steps.get-pull-request-number.outputs.pull_request_number }}
          comment-author: 'github-actions[bot]'
          body-includes: Screenshot Comparison Results

      - name: Add or update comment on PR
        uses: peter-evans/create-or-update-comment@e8674b075228eee787fea43ef493e45ece1004c9 # v5
        if: steps.prepare-companion-branch.outputs.comment_content != ''
        with:
          comment-id: ${{ steps.fc.outputs.comment-id }}
          issue-number: ${{ steps.get-pull-request-number.outputs.pull_request_number }}
          body: ${{ steps.prepare-companion-branch.outputs.comment_content }}
          edit-mode: replace

      - name: Cleanup outdated companion branches
        run: |
          # Find outdated companion branches with last commit date
          git branch -r --format="%(refname:lstrip=3)" | grep companion_ | while read -r branch; do
            last_commit_date_timestamp=$(git log -1 --format=%ct "origin/$branch")
            now_timestamp=$(date +%s)
            # Delete branch if it's older than 1 month
            if [ $((now_timestamp - last_commit_date_timestamp)) -gt 1209600 ]; then
               git push origin --delete "$branch"
            fi
          done
