name: Build

on:
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

    - name: Set up JDK 17
      uses: ./.github/actions/setup-java

    - name: Setup Gradle
      uses: ./.github/actions/setup-gradle

    - name: Inject secrets into local.properties
      run: echo "reward.server.url=${{ secrets.REWARD_SERVER_URL }}" >> local.properties

    - name: Run Tests
      run: ./gradlew testDebugUnitTest

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a # v7
      with:
        name: test-results
        path: |
          **/build/reports/tests/testDebugUnitTest/
